config/routes.rb
Rails.application.routes.draw do
  resources :relationships
  resources :members
  resources :families
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  # Render dynamic PWA files from app/views/pwa/* (remember to link manifest in application.html.erb)
  # get "manifest" => "rails/pwa#manifest", as: :pwa_manifest
  # get "service-worker" => "rails/pwa#service_worker", as: :pwa_service_worker

  get "/trees/:id" => "trees#show"
  post "/import" => "import#import_txt"

  # Defines the root path route ("/")
  # root "posts#index"
end

app/models/family.rb
class Family < ApplicationRecord
  validates :name, uniqueness: true

  has_many :members


  def ancestor
    members.order(:birth_date).first
  end
end

app/controllers/families_controller.rb
class FamiliesController < ApplicationController
  before_action :set_family, only: %i[ show edit update destroy ]

  # GET /families or /families.json
  def index
    @families = Family.all
  end

  # GET /families/1 or /families/1.json
  def show
  end

  # GET /families/new
  def new
    @family = Family.new
  end

  # GET /families/1/edit
  def edit
  end

  # POST /families or /families.json
  def create
    @family = Family.new(family_params)

    respond_to do |format|
      if @family.save
        format.html { redirect_to @family, notice: "Family was successfully created." }
        format.json { render :show, status: :created, location: @family }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @family.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /families/1 or /families/1.json
  def update
    respond_to do |format|
      if @family.update(family_params)
        format.html { redirect_to @family, notice: "Family was successfully updated." }
        format.json { render :show, status: :ok, location: @family }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @family.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /families/1 or /families/1.json
  def destroy
    @family.destroy!

    respond_to do |format|
      format.html { redirect_to families_path, status: :see_other, notice: "Family was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_family
      @family = Family.find(params.expect(:id))
    end

    # Only allow a list of trusted parameters through.
    def family_params
      params.expect(family: [ :name ])
    end
end

app/helpers/families_helper.rb
module FamiliesHelper
end

app/views/families/_family.html.erb
<div id="<%= dom_id family %>">
  <p>
    <strong>Name:</strong>
    <%= family.name %>
  </p>

</div>

app/views/families/_form.html.erb
<%= form_with(model: family) do |form| %>
  <% if family.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(family.errors.count, "error") %> prohibited this family from being saved:</h2>

      <ul>
        <% family.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div>
    <%= form.label :name, style: "display: block" %>
    <%= form.text_field :name %>
  </div>

  <div>
    <%= form.submit %>
  </div>
<% end %>

app/views/families/edit.html.erb
<% content_for :title, "Editing family" %>

<h1>Editing family</h1>

<%= render "form", family: @family %>

<br>

<div>
  <%= link_to "Show this family", @family %> |
  <%= link_to "Back to families", families_path %>
</div>

app/views/families/index.html.erb
<p style="color: green"><%= notice %></p>

<% content_for :title, "Families" %>

<h1>Families</h1>

<div id="families">
  <% @families.each do |family| %>
    <%= render family %>
    <p>
      <%= link_to "Show this family", family %>
    </p>
  <% end %>
</div>

<%= link_to "New family", new_family_path %>

app/views/families/new.html.erb
<% content_for :title, "New family" %>

<h1>New family</h1>

<%= render "form", family: @family %>

<br>

<div>
  <%= link_to "Back to families", families_path %>
</div>

app/views/families/show.html.erb
<p style="color: green"><%= notice %></p>

<%= render @family %>

<div>
  <%= link_to "Edit this family", edit_family_path(@family) %> |
  <%= link_to "Back to families", families_path %>

  <%= button_to "Destroy this family", @family, method: :delete %>
</div>