config/routes.rb
Rails.application.routes.draw do
  resources :relationships
  resources :members
  resources :families
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  # Render dynamic PWA files from app/views/pwa/* (remember to link manifest in application.html.erb)
  # get "manifest" => "rails/pwa#manifest", as: :pwa_manifest
  # get "service-worker" => "rails/pwa#service_worker", as: :pwa_service_worker

  get "/trees/:id" => "trees#show"
  post "/import" => "import#import_txt"

  # Defines the root path route ("/")
  # root "posts#index"
end

app/models/member.rb
class Member < ApplicationRecord
  validates :name, uniqueness: true
  belongs_to :family

  enum :gender, male: "male", female: "female"

  has_many :relationships, class_name: "Relationship", foreign_key: "member1_id"
  has_many :inverse_relationships, class_name: "Relationship", foreign_key: "member2_id"

  has_many :spouses, -> { where(relationships: { types: "spouse" }) },
           through: :relationships, source: :member2

  has_many :children, -> { where(relationships: { types: "child" }) },
           through: :inverse_relationships, source: :member1

  has_many :parents, -> { where(relationships: { types: "child" }) },
           through: :relationships, source: :member2

  has_many :siblings, -> { where(relationships: { types: "sibling" }) },
           through: :relationships, source: :member2

  scope :spouses_of, ->(member_id) {
    joins("INNER JOIN relationships ON members.id = relationships.member2_id OR members.id = relationships.member1_id")
      .where("relationships.types = ?", Relationship.types[:spouse])
      .where("relationships.member1_id = ? OR relationships.member2_id = ?", member_id, member_id)
      .where("members.id != ?", member_id)
  }

  def cousins
    parent_ids = parents.pluck(:id)
    uncle_aunt_ids = Relationship.where(member1_id: parent_ids, types: "sibling").pluck(:member2_id)
    cousin_ids = Relationship.where(member1_id: uncle_aunt_ids, types: "child").pluck(:member2_id)
    Member.where(id: cousin_ids)
  end

  def sisters_in_law
    spouse_sisters = spouses.joins(:siblings).where(gender: "female")
    sibling_wives = siblings.joins(:spouses).where(gender: "female")
    spouse_sisters.or(sibling_wives)
  end

  def brothers_in_law
    spouse_brothers = spouses.joins(:siblings).where(gender: "male")
    sibling_husbands = siblings.joins(:spouses).where(gender: "male")
    spouse_brothers.or(sibling_husbands)
  end

  def grandparents
    parent_ids = parents.pluck(:id)
    grandparent_ids = Relationship.where(member2_id: parent_ids, types: "child").pluck(:member1_id)
    Member.where(id: grandparent_ids)
  end

  validate :death_time_validation

  def death_time_validation
    message = "Birth date can't be greater than death date!"
    errors.add(:base, message) if death_date && (birth_date > death_date)
  end
end

app/controllers/members_controller.rb
class MembersController < ApplicationController
  before_action :set_member, only: %i[ show edit update destroy ]

  # GET /members or /members.json
  def index
    @members = Member.all
  end

  # GET /members/1 or /members/1.json
  def show
  end

  # GET /members/new
  def new
    @member = Member.new
  end

  # GET /members/1/edit
  def edit
  end

  # POST /members or /members.json
  def create
    @member = Member.new(member_params)

    respond_to do |format|
      if @member.save
        format.html { redirect_to @member, notice: "Member was successfully created." }
        format.json { render :show, status: :created, location: @member }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @member.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /members/1 or /members/1.json
  def update
    respond_to do |format|
      if @member.update(member_params)
        format.html { redirect_to @member, notice: "Member was successfully updated." }
        format.json { render :show, status: :ok, location: @member }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @member.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /members/1 or /members/1.json
  def destroy
    @member.destroy!

    respond_to do |format|
      format.html { redirect_to members_path, status: :see_other, notice: "Member was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_member
      @member = Member.find(params.expect(:id))
    end

    # Only allow a list of trusted parameters through.
    def member_params
      params.expect(member: [ :name, :gender, :birth_date, :death_date, :family_id ])
    end
end

app/helpers/members_helper.rb
module MembersHelper
end

app/views/members/_form.html.erb
<%= form_with(model: member) do |form| %>
  <% if member.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(member.errors.count, "error") %> prohibited this member from being saved:</h2>

      <ul>
        <% member.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="mb-3">
    <%= form.label :name, style: "display: block" %>
    <%= form.text_field :name %>
  </div>
  <div class="mb-3">
      <%= form.radio_button :gender, "male" %>
      <%= form.label :male %>
      <%= form.radio_button :gender, "female" %>
      <%= form.label :female  %>

  </div>

  <div class="mb-3">
    <%= form.label :birth_date, style: "display: block" %>
    <%= form.datetime_field :birth_date %>
  </div>

  <div class="mb-3">
    <%= form.label :death_date, style: "display: block" %>
    <%= form.datetime_field :death_date %>
  </div>

  <div class="mb-3">
    <%= form.label :family_id, style: "display: block" %>
    <%= form.select :family_id, Family.all.map {|r| [r.name, r.id]}  %>
  </div>

  <div class="mb-3">
    <%= form.submit %>
  </div>
<% end %>

app/views/members/_member.html.erb
<div id="<%= dom_id member %>">
  <p>
    <strong>Name:</strong>
    <%= member.name %>
  </p>

  <p>
    <strong>Gender:</strong>
    <%= member.gender %>
  </p>

  <p>
    <strong>Birth date:</strong>
    <%= member.birth_date %>
  </p>

  <p>
    <strong>Death date:</strong>
    <%= member.death_date %>
  </p>

  <p>
    <strong>Family:</strong>
    <%= member.family.name %>
  </p>

</div>

app/views/members/edit.html.erb
<% content_for :title, "Editing member" %>

<h1>Editing member</h1>

<%= render "form", member: @member %>

<br>

<div>
  <%= link_to "Show this member", @member %> |
  <%= link_to "Back to members", members_path %>
</div>

app/views/members/index.html.erb
<p style="color: green"><%= notice %></p>

<% content_for :title, "Members" %>

<h1>Members</h1>

<div id="members">
  <% @members.each do |member| %>
    <%= render member %>
    <p>
      <%= link_to "Show this member", member %>
    </p>
  <% end %>
</div>

<%= link_to "New member", new_member_path %>

app/views/members/new.html.erb
<% content_for :title, "New member" %>

<h1>New member</h1>

<%= render "form", member: @member %>

<br>

<div>
  <%= link_to "Back to members", members_path %>
</div>

app/views/members/show.html.erb
<p style="color: green"><%= notice %></p>

<%= render @member %>

<div>
  <%= link_to "Edit this member", edit_member_path(@member) %> |
  <%= link_to "Back to members", members_path %>

  <%= button_to "Destroy this member", @member, method: :delete %>
</div>